# Rustfmt Configuration for IPE
# High-quality formatting standards for security-critical code

# Edition
edition = "2021"

# Line width
max_width = 100
comment_width = 100

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Code style
fn_args_layout = "Tall"
fn_call_width = 80
struct_lit_width = 40
array_width = 80
chain_width = 80

# Formatting
use_small_heuristics = "Max"
newline_style = "Unix"
indent_style = "Block"
hard_tabs = false
tab_spaces = 4

# Trailing
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = true

# Spaces
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Documentation
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Misc
remove_nested_parens = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
