[package]
name = "ipe-ffi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
libc = { workspace = true }

[lib]
crate-type = ["cdylib", "staticlib"]
