services:
  docs:
    image: nginx:alpine
    container_name: ipe-docs
    ports:
      - "8080:8080"
    volumes:
      # Mount docs directory as read-only
      - ./:/usr/share/nginx/html:ro
      # Mount nginx config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      com.ipe.service: "documentation"
      com.ipe.description: "IPE Documentation and Performance Dashboards"

  # Optional: Playwright test runner
  playwright:
    image: mcr.microsoft.com/playwright:v1.40.0-focal
    container_name: ipe-playwright
    working_dir: /work
    volumes:
      - ./:/work
    environment:
      - CI=true
    network_mode: "host"
    command: ["npx", "playwright", "test"]
    depends_on:
      docs:
        condition: service_healthy
    profiles:
      - test

networks:
  default:
    name: ipe-docs-network
