apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipe.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipe.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- include "ipe.config" . | nindent 4 }}
